"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CheckCircle2 } from "lucide-react";

interface Receipt { receiptNumber:string;reference:string;email:string;productType:"CORE_ONBOARDING"|"ULTRA_PERIOD"|"RESEARCH_PACK";amountMinor:number;currency:string;seller:string;paymentMethod:string;providerPaymentReference:string;receiptIssuedAt:string;accessNotice:string }
function money(receipt:Receipt){return new Intl.NumberFormat("en-GB",{style:"currency",currency:receipt.currency}).format(receipt.amountMinor/100)}
const productName=(type:Receipt["productType"])=>type==="CORE_ONBOARDING"?"GridFlow Core onboarding":type==="ULTRA_PERIOD"?"GridFlow Ultra — 30 days":"GridFlow research credit pack";
export function ReceiptClient(){const [receipt,setReceipt]=useState<Receipt|null>(null);const [error,setError]=useState("");useEffect(()=>{const params=new URLSearchParams(window.location.hash.replace(/^#/,""));const receiptNumber=params.get("number");const token=params.get("token");window.history.replaceState(null,"",window.location.pathname);if(!receiptNumber||!token){setError("This receipt link is incomplete.");return;}fetch("/backend/commerce/receipts/lookup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({receiptNumber,token})}).then(async response=>{const body=await response.json() as Receipt&{message?:string};if(!response.ok)throw new Error(body.message??"Receipt lookup failed.");setReceipt(body);}).catch(cause=>setError(cause instanceof Error?cause.message:"Receipt lookup failed."));},[]);if(error)return <div className="receipt-state"><div className="notice notice-error">{error}</div><Link className="button button-secondary" href="/support">Get support</Link></div>;if(!receipt)return <div className="receipt-state">Loading receipt…</div>;return <article className="receipt-document"><div className="receipt-mark"><CheckCircle2/><span>Payment recorded</span></div><div className="receipt-heading"><div><div className="public-brand"><span>GRID</span>FLOW</div><h1>Payment receipt</h1></div><strong>{receipt.receiptNumber}</strong></div><dl><div><dt>Seller</dt><dd>{receipt.seller}</dd></div><div><dt>Product</dt><dd>{productName(receipt.productType)}</dd></div><div><dt>Amount</dt><dd>{money(receipt)}</dd></div><div><dt>Account email</dt><dd>{receipt.email}</dd></div><div><dt>Order reference</dt><dd>{receipt.reference}</dd></div><div><dt>Payment method</dt><dd>{receipt.paymentMethod}</dd></div><div><dt>Wise reference</dt><dd>{receipt.providerPaymentReference}</dd></div><div><dt>Receipt issued</dt><dd>{new Date(receipt.receiptIssuedAt).toLocaleString("en-GB",{timeZone:"UTC"})} UTC</dd></div></dl><p className="notice">{receipt.accessNotice}</p></article>}
