/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Building2, Linkedin, Mail, Phone } from "lucide-react";
import { ApiError, apiGet } from "../../../lib/server-api";
import { Shell } from "../../../components/shell";
import { StatusBadge } from "../../../components/status-badge";
import { EmptyState } from "../../../components/empty-state";
import { RunAgentButton } from "../../../components/run-agent-button";
import { ContactEditor } from "./contact-editor";
export const dynamic="force-dynamic";
type Item=Record<string,any>;
interface Detail{contact:Item;outreach:Item[];interactions:Item[];tasks:Item[];meetings:Item[];evidence:Item[];opportunities:Item[];agentRuns:Item[]}
const dt=(v:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const money=(m:number,c="GBP")=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c,maximumFractionDigits:0}).format(m/100);
export default async function ContactPage({params}:{params:Promise<{id:string}>}){const{id}=await params;let d:Detail;try{d=await apiGet<Detail>(`/contacts/${id}`)}catch(e){if(e instanceof ApiError&&e.status===404)notFound();throw e}const c=d.contact;const eligible=["NOT_STARTED","FAILED","DRAFT_READY"].includes(c.echoStatus)&&Boolean(c.email||c.linkedinProfileUrl)&&["PRIMARY","SECONDARY"].includes(c.contactPriority)&&["HIGH","MEDIUM"].includes(c.companyPriority||"");return <Shell title={c.contactName}>
<div className="detail-hero"><div className="detail-identity"><span className="detail-logo">{c.contactName.split(" ").map((x:string)=>x[0]).join("").slice(0,2).toUpperCase()}</span><div><Link className="table-sub" href="/contacts"><ArrowLeft size={12}/> Back to contacts</Link><h1>{c.contactName}</h1><div className="detail-meta"><span>{c.jobTitle}</span><Link href={`/companies/${c.companyId}`}>{c.companyName}</Link><StatusBadge value={c.contactPriority}/><StatusBadge value={c.status}/><StatusBadge value={c.verificationStatus}/></div></div></div><div className="detail-actions">{c.email?<a className="button button-secondary" href={`mailto:${c.email}`}><Mail size={14}/>Email</a>:null}{c.linkedinProfileUrl?<a className="button button-secondary" href={c.linkedinProfileUrl} target="_blank" rel="noreferrer"><Linkedin size={14}/>LinkedIn</a>:null}{c.phone?<a className="button button-secondary" href={`tel:${c.phone}`}><Phone size={14}/>Call</a>:null}{eligible?<RunAgentButton agentName="ECHO" contactId={c.id} label={c.echoStatus==="DRAFT_READY"?"Regenerate Echo":"Run Echo"} forceRegenerate={c.echoStatus==="DRAFT_READY"}/>:null}</div></div>
<div className="split-layout"><div className="stack"><section className="card"><div className="section-header"><div><div className="eyebrow">Relationship context</div><h2>Contact intelligence</h2></div><StatusBadge value={c.echoStatus}/></div><div className="grid-3"><div className="score-card"><strong>{c.confidence!==null&&c.confidence!==undefined?`${Math.round(c.confidence*100)}%`:"—"}</strong><span>Confidence</span></div><div className="score-card"><strong>{c.evidenceCompleteness!==null&&c.evidenceCompleteness!==undefined?`${Math.round(c.evidenceCompleteness*100)}%`:"—"}</strong><span>Evidence complete</span></div><div className="score-card"><strong>{c.preferredChannel.replaceAll("_"," ")}</strong><span>Preferred channel</span></div></div>{c.notes?<div className="rich-copy section-gap">{c.notes}</div>:null}</section>
<section className="card"><div className="section-header"><div><div className="eyebrow">Outreach history</div><h2>Message versions and channel actions</h2></div><Link className="button button-secondary" href="/outreach">Open workbench</Link></div>{d.outreach.length===0?<EmptyState title="No outreach exists" copy="Run Echo to generate the first evidence-backed message set."/>:<div className="queue">{d.outreach.map(x=><Link className="queue-item" href={`/outreach/${x.id}`} key={x.id}><div className="queue-main"><div className="queue-title">{x.outreachName}</div><div className="queue-copy">{x.emailSubject||x.linkedinConnectionNote||"Message content unavailable"} · version {x.versionNumber??0}</div></div><div className="queue-meta"><StatusBadge value={x.approvalStatus}/><StatusBadge value={x.linkedinStatus}/></div></Link>)}</div>}</section>
<div className="grid-2 balanced"><section className="card"><div className="section-header"><div><div className="eyebrow">Activity</div><h2>Interaction timeline</h2></div><Link className="button button-ghost" href="/interactions">All interactions</Link></div>{d.interactions.length===0?<EmptyState title="No interactions recorded" copy="Manual notes and completed channel actions will create a permanent history."/>:<div className="timeline">{d.interactions.map(x=><div className="timeline-item" key={x.id}><span className="timeline-dot"/><div><div className="timeline-title">{x.summary}</div><div className="timeline-copy">{x.outcome}</div><div className="timeline-time">{x.channel||x.direction} · {dt(x.occurredAt)}</div></div></div>)}</div>}</section><section className="card"><div className="section-header"><div><div className="eyebrow">Evidence</div><h2>Verification sources</h2></div><span className="badge neutral">{d.evidence.length}</span></div>{d.evidence.length===0?<EmptyState title="No evidence attached" copy="Relay sources will appear here when the contact is discovered or verified."/>:<div className="evidence-list">{d.evidence.map(x=><div className="evidence-item" key={x.id}><a href={x.url} target="_blank" rel="noreferrer">{x.title||x.publisher||x.url}</a><p>{[x.publisher,x.claimKey,x.retrievedAt?dt(x.retrievedAt):null].filter(Boolean).join(" · ")}</p></div>)}</div>}</section></div>
<section className="card"><div className="section-header"><div><div className="eyebrow">Commercial conversion</div><h2>Opportunities</h2></div><Link className="button button-primary" href={`/opportunities?company=${c.companyId}&contact=${c.id}`}>Create opportunity</Link></div>{d.opportunities.length===0?<EmptyState title="No opportunity linked" copy="Create one once the contact confirms meaningful interest."/>:<div className="queue">{d.opportunities.map(x=><Link className="queue-item" href="/opportunities" key={x.id}><div className="queue-main"><div className="queue-title">{x.opportunityName}</div><div className="queue-copy">{x.probability}% probability</div></div><div className="queue-meta"><strong>{x.valueMinor?money(x.valueMinor,x.currency):"Value TBD"}</strong><StatusBadge value={x.stage}/></div></Link>)}</div>}</section></div>
<aside className="stack"><section className="card"><div className="section-header"><div><div className="eyebrow">Workspace controls</div><h2>Manage relationship</h2></div></div><ContactEditor contact={c as any}/></section><section className="card soft"><div className="section-header"><div><div className="eyebrow">Company context</div><h2>{c.companyName}</h2></div><Building2 size={17}/></div><div className="rich-copy">Priority: {c.companyPriority||"Unassigned"}<br/>Commercial stage: {c.companyStage.replaceAll("_"," ")}<br/>Website: {c.website}</div><Link className="button button-secondary section-gap" href={`/companies/${c.companyId}`}>Open company <ArrowUpRight size={14}/></Link></section><section className="card"><div className="section-header"><div><div className="eyebrow">Next actions</div><h2>Tasks and meetings</h2></div></div><div className="queue">{d.tasks.slice(0,5).map(x=><Link className="queue-item" href="/tasks" key={x.id}><div className="queue-main"><div className="queue-title">{x.title}</div><div className="queue-copy">{x.dueAt?dt(x.dueAt):"No due date"}</div></div><StatusBadge value={x.status}/></Link>)}{d.meetings.slice(0,3).map(x=><Link className="queue-item" href="/meetings" key={x.id}><div className="queue-main"><div className="queue-title">{x.title}</div><div className="queue-copy">{dt(x.startsAt)}</div></div><StatusBadge value="MEETING_SCHEDULED"/></Link>)}{d.tasks.length===0&&d.meetings.length===0?<EmptyState title="No follow-up planned" copy="Add a task or meeting so this relationship never disappears into a spreadsheet."/>:null}</div></section></aside></div></Shell>}
