/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Globe2, Linkedin, Mail, Phone, Sparkles } from "lucide-react";
import { ApiError, apiGet } from "../../../lib/server-api";
import { Shell } from "../../../components/shell";
import { StatusBadge } from "../../../components/status-badge";
import { EmptyState } from "../../../components/empty-state";
import { RunAgentButton } from "../../../components/run-agent-button";
import { CompanyEditor } from "./company-editor";
export const dynamic="force-dynamic";

type Item=Record<string,any>;
interface CompanyDetail{company:Item;contacts:Item[];outreach:Item[];opportunities:Item[];tasks:Item[];interactions:Item[];meetings:Item[];evidence:Item[];agentRuns:Item[]}
const money=(minor:number,currency="GBP")=>new Intl.NumberFormat("en-GB",{style:"currency",currency,maximumFractionDigits:0}).format(minor/100);
const dt=(v:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
export default async function CompanyDetailPage({params}:{params:Promise<{id:string}>}){const{id}=await params;let data:CompanyDetail;try{data=await apiGet<CompanyDetail>(`/companies/${id}`)}catch(e){if(e instanceof ApiError&&e.status===404)notFound();throw e}const c=data.company;const scoreFields=[["Budget",c.budgetPotential],["Strategic fit",c.strategicFit],["Geography",c.geographicalFit],["Sport relevance",c.motorsportRelevance],["Marketing",c.marketingActivity],["Access",c.decisionMakerAccess],["Timing",c.timingScore]];const sageReady=["UNRESEARCHED","NEED_REVIEW"].includes(c.researchStatus);const relayReady=c.researchStatus==="RESEARCHED"&&["HIGH","MEDIUM"].includes(c.priority||"");return <Shell title={c.companyName}>
 <div className="detail-hero"><div className="detail-identity"><span className="detail-logo">{c.companyName.slice(0,2).toUpperCase()}</span><div><Link className="table-sub" href="/companies"><ArrowLeft size={12}/> Back to companies</Link><h1>{c.companyName}</h1><div className="detail-meta"><span>{c.country||"Market unknown"}</span><span>{c.industries||"Industry not classified"}</span><span>{c.companySize||"Company size unknown"}</span><StatusBadge value={c.currentStage}/><StatusBadge value={c.priority}/></div></div></div><div className="detail-actions"><a className="button button-secondary" href={c.website} target="_blank" rel="noreferrer"><Globe2 size={14}/>Website</a>{c.linkedinCompanyUrl?<a className="button button-secondary" href={c.linkedinCompanyUrl} target="_blank" rel="noreferrer"><Linkedin size={14}/>LinkedIn</a>:null}{sageReady?<RunAgentButton agentName="SAGE" companyId={c.id} label="Run Sage"/>:relayReady?<RunAgentButton agentName="RELAY" companyId={c.id} label="Run Relay"/>:null}</div></div>
 <div className="split-layout"><div className="stack">
  <section className="card"><div className="section-header"><div><div className="eyebrow">Commercial intelligence</div><h2>Why this company fits</h2></div><div style={{display:"flex",alignItems:"center",gap:8}}><span className="score-pill">{c.commercialScore??"—"}</span><StatusBadge value={c.researchStatus}/></div></div><div className="rich-copy">{c.discoveryRationale||"Atlas has not recorded a discovery rationale yet."}</div>{c.partnershipAngle?<><div className="section-gap"><div className="eyebrow">Recommended partnership angle</div><div className="rich-copy" style={{marginTop:8}}>{c.partnershipAngle}</div></div></>:null}<div className="score-grid section-gap">{scoreFields.map(([label,value])=><div className="score-card" key={String(label)}><strong>{value??"—"}<small>/5</small></strong><span>{label}</span></div>)}</div></section>
  <section className="card"><div className="section-header"><div><div className="eyebrow">Decision-makers</div><h2>Contacts</h2><p>{c.recommendedContactRoles||"Relay recommendations will appear after company research."}</p></div><StatusBadge value={c.contactDiscoveryStatus}/></div>{data.contacts.length===0?<EmptyState title="No contacts yet" copy="Run Relay after Sage has completed the company research."/>:<div className="table-wrap"><table><thead><tr><th>Contact</th><th>Priority</th><th>Channel</th><th>Echo</th><th></th></tr></thead><tbody>{data.contacts.map(x=><tr key={x.id}><td><Link className="table-link" href={`/contacts/${x.id}`}><div className="table-primary">{x.contactName}</div><div className="table-sub">{x.jobTitle} · {x.department.replaceAll("_"," ")}</div></Link></td><td><StatusBadge value={x.contactPriority}/></td><td><div className="row-actions" style={{justifyContent:"flex-start"}}>{x.email?<Mail size={13}/>:null}{x.linkedinProfileUrl?<Linkedin size={13}/>:null}{x.phone?<Phone size={13}/>:null}</div></td><td><StatusBadge value={x.echoStatus}/></td><td><Link className="icon-button" href={`/contacts/${x.id}`}><ArrowUpRight size={14}/></Link></td></tr>)}</tbody></table></div>}</section>
  <section className="card"><div className="section-header"><div><div className="eyebrow">Outreach</div><h2>Messages and channel status</h2></div><Link className="button button-secondary" href="/outreach">Open workbench</Link></div>{data.outreach.length===0?<EmptyState title="No outreach generated" copy="Run Echo on an eligible contact to create a reviewable message set."/>:<div className="queue">{data.outreach.map(x=><Link href={`/outreach/${x.id}`} className="queue-item" key={x.id}><div className="queue-main"><div className="queue-title">{x.contactName}</div><div className="queue-copy">{x.emailSubject||x.linkedinConnectionNote||"Draft content unavailable"}</div></div><div className="queue-meta"><StatusBadge value={x.approvalStatus}/><StatusBadge value={x.linkedinStatus}/></div></Link>)}</div>}</section>
  <section className="card"><div className="section-header"><div><div className="eyebrow">Pipeline</div><h2>Opportunities</h2></div><Link className="button button-primary" href={`/opportunities?company=${c.id}`}>Create opportunity</Link></div>{data.opportunities.length===0?<EmptyState title="No opportunity created" copy="Create an opportunity when the company shows commercial interest."/>:<div className="queue">{data.opportunities.map(x=><Link href={`/opportunities/${x.id}`} className="queue-item" key={x.id}><div className="queue-main"><div className="queue-title">{x.opportunityName}</div><div className="queue-copy">{x.primaryContactName||"No primary contact"} · {x.probability}% probability</div></div><div className="queue-meta"><strong>{x.valueMinor?money(x.valueMinor,x.currency):"Value TBD"}</strong><StatusBadge value={x.stage}/></div></Link>)}</div>}</section>
  <div className="grid-2 balanced"><section className="card"><div className="section-header"><div><div className="eyebrow">Timeline</div><h2>Interactions</h2></div><Link className="button button-ghost" href="/interactions">All</Link></div>{data.interactions.length===0?<EmptyState title="No activity" copy="Calls, emails, LinkedIn actions and notes will appear here."/>:<div className="timeline">{data.interactions.slice(0,8).map(x=><div className="timeline-item" key={x.id}><span className="timeline-dot"/><div><div className="timeline-title">{x.summary}</div><div className="timeline-copy">{[x.contactName,x.outcome].filter(Boolean).join(" · ")}</div><div className="timeline-time">{x.channel||x.direction} · {dt(x.occurredAt)}</div></div></div>)}</div>}</section><section className="card"><div className="section-header"><div><div className="eyebrow">Evidence</div><h2>Research sources</h2></div><span className="badge neutral">{data.evidence.length}</span></div>{data.evidence.length===0?<EmptyState title="No evidence attached" copy="Evidence-backed Sage and Relay runs will populate this section."/>:<div className="evidence-list">{data.evidence.slice(0,8).map(x=><div className="evidence-item" key={x.id}><a href={x.url} target="_blank" rel="noreferrer">{x.title||x.publisher||x.url}</a><p>{[x.publisher,x.claimKey,x.retrievedAt?dt(x.retrievedAt):null].filter(Boolean).join(" · ")}</p></div>)}</div>}</section></div>
 </div><aside className="stack"><section className="card"><div className="section-header"><div><div className="eyebrow">Workspace controls</div><h2>Manage company</h2></div></div><CompanyEditor company={c as any}/></section><section className="card soft"><div className="section-header"><div><div className="eyebrow">Research state</div><h2>Agent history</h2></div><Sparkles size={17}/></div>{data.agentRuns.length===0?<div className="rich-copy">No agent runs are linked to this company.</div>:<div className="queue">{data.agentRuns.slice(0,7).map(x=><Link href="/agent-runs" className="queue-item" key={x.id}><div className="queue-main"><div className="queue-title">{x.agentName}</div><div className="queue-copy">{x.modelUsed||"Model not recorded"} · {x.promptVersion||"Prompt version not recorded"}</div></div><StatusBadge value={x.status}/></Link>)}</div>}</section><section className="card"><div className="section-header"><div><div className="eyebrow">Next actions</div><h2>Tasks and meetings</h2></div></div><div className="queue">{data.tasks.slice(0,5).map(x=><Link className="queue-item" href="/tasks" key={x.id}><div className="queue-main"><div className="queue-title">{x.title}</div><div className="queue-copy">{x.dueAt?dt(x.dueAt):"No due date"}</div></div><StatusBadge value={x.status}/></Link>)}{data.meetings.slice(0,3).map(x=><Link className="queue-item" href="/meetings" key={x.id}><div className="queue-main"><div className="queue-title">{x.title}</div><div className="queue-copy">{dt(x.startsAt)}</div></div><StatusBadge value="MEETING_SCHEDULED"/></Link>)}{data.tasks.length===0&&data.meetings.length===0?<EmptyState title="No next action" copy="Create a task or schedule a meeting to keep this account moving."/>:null}</div></section></aside></div>
 </Shell>}
