"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { ArrowRight, CalendarClock, ShieldAlert, TrendingUp } from "lucide-react";
import { StatusBadge } from "../../components/status-badge";

interface RenewalRow {programmeId:string;programmeStatus:string;renewalReviewDate:string|null;renewalStatus:string;deliveryEndDate:string;contractTitle:string;contractNumber:string;valueMinor:number;currency:string;companyName:string;caseId:string|null;caseStatus:string;intent:string|null;sponsorSentiment:string|null;expectedDecisionDate:string|null;opportunityId:string|null;totalObligations:number;resolvedObligations:number;deliveryRisks:number;sharedReports:number}
export interface RenewalsOverview {summary:{eligible:number;draft:number;awaitingApproval:number;active:number;renewed:number;due:number};cases:RenewalRow[]}
const money=(minor:number,code:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:code,maximumFractionDigits:0}).format(Number(minor)/100);
const dateLabel=(value:string|null)=>value?new Date(value).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"}):"Not scheduled";

export function RenewalsCockpit({data}:{data:RenewalsOverview}){
  const router=useRouter();const [filter,setFilter]=useState<"ACTION"|"PIPELINE"|"COMPLETE"|"ALL">("ACTION");const [busy,setBusy]=useState("");const [error,setError]=useState("");
  const visible=useMemo(()=>data.cases.filter(item=>filter==="ALL"||(filter==="ACTION"&&(!item.caseId||["DRAFT","REVIEW_READY"].includes(item.caseStatus)||Number(item.deliveryRisks)>0))||(filter==="PIPELINE"&&["APPROVED","HANDED_OFF","ON_HOLD"].includes(item.caseStatus))||(filter==="COMPLETE"&&["RENEWED","DECLINED"].includes(item.caseStatus))),[data.cases,filter]);
  async function prepare(programmeId:string){setBusy(programmeId);setError("");try{const response=await fetch(`/backend/renewals/programmes/${programmeId}/prepare`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:"{}"});const body=await response.json().catch(()=>({})) as {caseId?:string;message?:string|string[]};if(!response.ok)throw new Error(Array.isArray(body.message)?body.message.join(" "):body.message||"Renewal case could not be prepared.");if(body.caseId)router.push(`/renewals/${body.caseId}`);else router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Renewal case could not be prepared.");}finally{setBusy("");}}
  return <div className="stack section-gap"><div className="grid-6 forge-metrics"><article className="metric-card"><span>Eligible</span><strong>{data.summary.eligible}</strong><small>Delivered partnerships</small></article><article className="metric-card"><span>Due</span><strong>{data.summary.due}</strong><small>Review date reached</small></article><article className="metric-card"><span>Drafts</span><strong>{data.summary.draft}</strong><small>Briefs in preparation</small></article><article className="metric-card"><span>Approve</span><strong>{data.summary.awaitingApproval}</strong><small>Human review required</small></article><article className="metric-card"><span>Pipeline</span><strong>{data.summary.active}</strong><small>Approved or handed off</small></article><article className="metric-card"><span>Renewed</span><strong>{data.summary.renewed}</strong><small>Confirmed outcomes</small></article></div>{error?<div className="notice notice-error" role="alert">{error}</div>:null}<div className="toolbar"><div className="toolbar-group">{(["ACTION","PIPELINE","COMPLETE","ALL"] as const).map(value=><button className={`button ${filter===value?"button-primary":"button-secondary"}`} type="button" key={value} onClick={()=>setFilter(value)}>{value[0]}{value.slice(1).toLowerCase()}</button>)}</div></div><div className="forge-list">{visible.length?visible.map(item=>{const risk=Number(item.deliveryRisks)>0;const content=<><span className="metric-icon">{risk?<ShieldAlert size={17}/>:<TrendingUp size={17}/>}</span><div className="queue-main"><div className="queue-title">{item.companyName}</div><div className="queue-copy">{item.contractTitle} · {item.contractNumber}</div><div className="table-sub">{money(item.valueMinor,item.currency)} · {item.resolvedObligations}/{item.totalObligations} obligations resolved · {item.sharedReports} reports shared</div></div><div className="queue-meta"><StatusBadge value={risk?"AT_RISK":item.caseStatus}/><span className="delivery-renewal-chip"><CalendarClock size={13}/>{dateLabel(item.renewalReviewDate||item.deliveryEndDate)}</span>{item.caseId?<ArrowRight size={16}/>:null}</div></>;return item.caseId?<Link className="card forge-row" href={`/renewals/${item.caseId}`} key={item.programmeId}>{content}</Link>:<article className="card forge-row" key={item.programmeId}>{content}<button className="button button-primary" type="button" disabled={Boolean(busy)} onClick={()=>prepare(item.programmeId)}>{busy===item.programmeId?"Preparing…":"Prepare renewal"}</button></article>;}):<div className="empty-state"><strong>No renewals in this view.</strong><p>Renewal cases appear from active or completed Delivery programmes.</p></div>}</div></div>;
}
