import{BadRequestException,Injectable}from"@nestjs/common";import{DatabaseService}from"../database/database.service.js";
const directions=["INBOUND","OUTBOUND","INTERNAL"]as const;const channels=["LINKEDIN","EMAIL","PHONE"]as const;
export interface CreateInteractionInput{summary?:string;outcome?:string|null;direction?:string;channel?:string|null;occurredAt?:string;companyId?:string|null;contactId?:string|null;opportunityId?:string|null;outreachRecordId?:string|null;}
@Injectable()export class InteractionsService{constructor(private readonly db:DatabaseService){}async list(t:string){return this.db.tenantTransaction(t,async x=>(await x.query(
 `SELECT i."id",i."summary",i."outcome",i."direction"::text AS "direction",i."channel"::text AS "channel",i."occurredAt",i."source"::text AS "source",c."companyName",ct."contactName",o."opportunityName"
  FROM "Interaction" i LEFT JOIN "Company" c ON c."id"=i."companyId" LEFT JOIN "Contact" ct ON ct."id"=i."contactId" LEFT JOIN "Opportunity" o ON o."id"=i."opportunityId"
  WHERE i."tenantId"=$1::uuid ORDER BY i."occurredAt" DESC LIMIT 250`,[t])).rows)}async create(t:string,b:CreateInteractionInput){if(!b.summary?.trim())throw new BadRequestException("Interaction summary is required.");if(b.direction&&!directions.includes(b.direction as never))throw new BadRequestException("Invalid interaction direction.");if(b.channel&&!channels.includes(b.channel as never))throw new BadRequestException("Invalid channel.");return this.db.tenantTransaction(t,async x=>{const r=await x.query<{id:string}>(
 `INSERT INTO "Interaction" ("tenantId","companyId","contactId","outreachRecordId","opportunityId","channel","direction","summary","outcome","occurredAt") VALUES ($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::"ChannelType",$7::"InteractionDirection",$8,$9,COALESCE($10::timestamptz,CURRENT_TIMESTAMP)) RETURNING "id"`,
 [t,b.companyId??null,b.contactId??null,b.outreachRecordId??null,b.opportunityId??null,b.channel??null,b.direction??"INTERNAL",b.summary!.trim(),b.outcome??null,b.occurredAt??null]);return{id:r.rows[0]?.id};})}}
