import type { Metadata } from "next";
import { LegalContact, LegalPage } from "../../../components/legal-page";
import { PublicShell } from "../../../components/public-shell";

export const metadata: Metadata = { title: "Retention Schedule | GridFlow", description: "How long GridFlow keeps different data classes." };

export default function RetentionPage() {
  return <PublicShell><LegalPage eyebrow="Data lifecycle" title="Retention Schedule" summary="Current operational periods, subject to legal holds and the principle of keeping only what is needed.">
    <section><h2>Current schedule</h2><div className="legal-table"><div><strong>Data class</strong><strong>Normal rule</strong></div><div><span>Active account and workspace data</span><span>For the account/contract plus a 30-day controlled closure window, then deletion or anonymisation unless the customer requests an earlier lawful action.</span></div><div><span>Sessions and trusted devices</span><span>Session up to 30 days; trusted device up to 365 days; earlier on logout, replacement or revocation. Revoked security records may be retained up to 12 months for abuse investigation.</span></div><div><span>Password reset, MFA and activation challenges</span><span>Short expiry configured by purpose; expired/used challenge records removed or anonymised within 90 days unless needed for a security investigation.</span></div><div><span>Public-source research and contact provenance</span><span>Reviewed during use and at least every 12 months; stale/unneeded contact data deleted. Objection/suppression evidence retained while outreach could otherwise recur, normally for the account plus 6 years.</span></div><div><span>Gmail/OAuth and customer API keys</span><span>While connected/needed; tokens and keys revoked and deleted on disconnect or closure, subject to short operational recovery copies and provider-side rules.</span></div><div><span>AI prompts, outputs and usage telemetry</span><span>Workspace content follows the account period. Detailed operational/cost telemetry normally up to 12 months, then aggregated or deleted.</span></div><div><span>Support and privacy requests</span><span>Normally 3 years after closure of the request, longer where needed for a dispute, regulator or legal obligation.</span></div><div><span>Quotes, invoices, receipts and payment records</span><span>Normally 6 years after the end of the relevant financial year, subject to accounting/tax requirements.</span></div><div><span>Legal acceptance and key security audit evidence</span><span>Contract term plus up to 6 years to establish or defend legal claims; high-volume operational logs normally 12 months.</span></div><div><span>Backups</span><span>Protected rolling backups expire through the configured hosting rotation, targeted at no more than 35 days. Deleted data is not restored to active service except for disaster recovery and is re-deleted through the normal process.</span></div></div></section>
    <section><h2>Exceptions and review</h2><p>We may preserve specific data under a documented legal hold, fraud/security investigation or statutory duty, and may delete data earlier when it is no longer needed. Production backup periods, provider retention and scheduled deletion jobs must be verified in the final launch evidence. This schedule does not promise instant deletion from immutable or isolated recovery copies.</p></section>
    <LegalContact/>
  </LegalPage></PublicShell>;
}
