import type { Metadata } from "next";
import Link from "next/link";
import { CreditCard, KeyRound, LifeBuoy } from "lucide-react";
import { PublicShell } from "../../components/public-shell";
import { apiGet } from "../../lib/server-api";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Support | GridFlow",description:"Purchase, activation and account support for GridFlow."};

export default async function SupportPage(){let email:string|null=null;try{email=(await apiGet<{supportEmail:string|null}>("/commerce/catalogue")).supportEmail;}catch{}return <PublicShell><section className="public-page-hero"><div className="public-kicker">Support</div><h1>Get unstuck without exposing private access details.</h1><p>Choose the route that matches the problem. Never include passwords, activation tokens, receipt access tokens, API keys, recovery codes or OAuth secrets in a support message.</p></section><section className="public-section"><div className="public-support-grid"><article><CreditCard/><h2>Purchase or payment</h2><p>For a Core quote, Wise payment verification, Ultra renewal or missing receipt, include only your name, account email and the Wise reference if one already exists.</p>{email?<a className="button button-secondary" href={`mailto:${email}?subject=GridFlow%20purchase%20support`}>Email purchase support</a>:<p className="notice">Direct purchase support will appear here when the release owner configures it. Do not send money until GridFlow supplies the correct Wise instructions.</p>}</article><article><KeyRound/><h2>Activation</h2><p>Core activation links are single-use, expiring and bound to the named driver’s email. Registration does not unlock the workspace until owner approval.</p><Link className="button button-secondary" href="/signup">Open activation screen</Link></article><article><LifeBuoy/><h2>Existing account</h2><p>Sign in for the permanent in-product manual, guided workflows, credit balance and account recovery. Use password reset if credentials are the only blocker.</p><div className="public-actions"><Link className="button button-secondary" href="/login">Sign in</Link><Link className="button button-secondary" href="/forgot-password">Reset password</Link></div></article></div></section></PublicShell>}
