import type { Metadata } from "next";
import Link from "next/link";
import { GRIDFLOW_LEGAL } from "@gridflow/domain";
import { LegalContact, LegalPage } from "../../../components/legal-page";
import { PublicShell } from "../../../components/public-shell";

export const metadata: Metadata = { title: "Terms of Service | GridFlow", description: "Terms governing access to and use of GridFlow." };

export default function TermsPage() {
  return <PublicShell><LegalPage eyebrow="Agreement" title="Terms of Service" summary="The rules for GridFlow access, purchases, outreach, AI assistance and customer responsibilities.">
    <section><h2>1. Agreement and eligibility</h2><p>These Terms govern your use of GridFlow. By creating an account, accepting an invitation, or using GridFlow, you accept the current version of these Terms and the <Link href="/legal/privacy">Privacy Policy</Link>. You must be at least {GRIDFLOW_LEGAL.minimumAge} and have authority to act for the organisation you register. If you use GridFlow for trade or professional purposes you are a “Business User”; otherwise you may be a “Consumer”. Mandatory consumer rights are not excluded.</p></section>
    <section><h2>2. What GridFlow provides</h2><p>GridFlow is a sponsorship commercial operating system for research, relationships, outreach preparation, proposals, contracts, delivery evidence and renewals. Features may include human-reviewed AI assistance and connected Gmail workflows. GridFlow does <strong>not</strong> guarantee sponsors, replies, meetings, revenue, contract signatures or any sporting result. You remain responsible for commercial judgment and every external commitment.</p></section>
    <section><h2>3. Access, activation and accounts</h2><p>Core registration uses a private, email-bound, single-use activation issued after payment verification. Registration can remain pending until GridFlow approves it. We may reject, suspend or revoke access for payment mismatch, abuse, security risk, sanctions/legal risk or breach of these Terms.</p><p>Keep credentials private, use MFA when available, and notify us promptly of suspected compromise. Each person may use no more than two active trusted devices unless we approve otherwise. Do not share accounts or bypass role, seat, credit, activation or device controls.</p></section>
    <section><h2>4. Plans, quotes, payments and renewal</h2><ul><li><strong>Core:</strong> one-time access to the Core application, sold at an individually quoted price. The quote/invoice sets included seats, credits, taxes and any customer-specific work.</li><li><strong>Ultra:</strong> an optional managed layer supplied for a stated 30-day period. It does not renew or charge automatically. Another period begins only after a new arrangement and verified payment.</li><li><strong>Research credits:</strong> metered service units with the quantity, price, availability and any expiry shown before purchase. Credits are not money, transferable property or redeemable for cash.</li></ul><p>Payments follow the instructions supplied in the individual GridFlow quote or invoice and are manually verified by an authorised GridFlow administrator. A receipt confirms the recorded payment; Core access also remains subject to activation and approval. Unless a written quote says otherwise, prices are in GBP and any applicable taxes will be shown or explained before agreement.</p></section>
    <section><h2>5. Consumer cancellation and refunds</h2><p>If you are a Consumer, any non-waivable cancellation, digital-content, service-quality and refund rights under applicable law remain intact. Before immediate supply of digital content or services during a statutory cancellation period, GridFlow must obtain any express request and acknowledgement required by law; if that has not happened, these Terms do not pretend that the right was lost. Business User refunds and cancellations follow the written quote, except where law requires otherwise. Contact <a href={`mailto:${GRIDFLOW_LEGAL.supportEmail}`}>{GRIDFLOW_LEGAL.supportEmail}</a> with the purchase reference. Ultra ends automatically after its paid period, so no cancellation is needed to stop renewal.</p></section>
    <section><h2>6. Customer data and lawful outreach</h2><p>You control what authorised users place in the workspace and grant us the limited rights needed to host, secure, back up and process it to provide GridFlow. You must have a lawful basis and any required notices or permissions for personal data, mailbox data and outreach. Public availability alone is not permission to spam.</p><p>Respect objections and suppression records, verify contact provenance, identify yourself honestly, and comply with UK GDPR, PECR, consumer, advertising, anti-bribery, sanctions and other applicable rules. Do not fabricate identity, performance, evidence, social proof or commercial claims. LinkedIn actions remain user-performed unless a separately approved compliant integration exists.</p></section>
    <section><h2>7. AI and integrations</h2><p>AI output is assistance, not fact, legal advice or authority. Review source evidence, recipient, claims, prices, rights and tone before use. You may not use GridFlow or model output for unlawful profiling, deception, harassment, high-impact decisions, malware or attempts to extract another customer’s data, system prompts or secrets.</p><p>Third-party services such as Gmail, Gemini and Wise have their own terms and availability. You authorise the access you connect and can disconnect supported integrations. You are responsible for a customer-provided API key and its provider charges. GridFlow is not liable for a third party’s independent acts outside our reasonable control, but this does not remove rights that cannot lawfully be excluded.</p></section>
    <section><h2>8. Acceptable use</h2><p>Do not attack, scrape, reverse engineer, overload, probe or bypass GridFlow; upload malicious code; access data without permission; resell or sublicense the service; infringe rights; send unlawful messages; or use the service to build a competing dataset or product except where law does not allow that restriction. Reasonable security research must be authorised in writing.</p></section>
    <section><h2>9. Intellectual property</h2><p>We and our licensors own GridFlow, its software, brand and documentation. Subject to payment and these Terms, we grant you a limited, non-exclusive, non-transferable right to use the purchased service for your own organisation. You retain rights in your data. Feedback may be used without obligation if it does not identify you or reveal confidential information.</p></section>
    <section><h2>10. Availability, changes and support</h2><p>We aim to provide a reliable service but do not promise uninterrupted or error-free availability. Maintenance, emergencies, providers and security events can affect access. We may improve or replace features while preserving the substance of a paid entitlement. Material adverse changes will be communicated reasonably. Support is available through <Link href="/support">GridFlow Support</Link>.</p></section>
    <section><h2>11. Suspension, closure and termination</h2><p>You may request account closure in the <Link href="/privacy">Privacy Centre</Link>. We may suspend access where reasonably necessary to protect users, data, the service or legal compliance, and will give notice where appropriate. On termination, licences end and active integrations/sessions are revoked. Data handling follows the Privacy Policy and Retention Schedule; payment, IP, confidentiality, liability and dispute provisions intended to survive will survive.</p></section>
    <section><h2>12. Warranties and liability</h2><p>Nothing excludes liability that cannot legally be excluded, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or mandatory consumer remedies. GridFlow is not professional legal, tax, financial or sponsorship advice.</p><p>For Business Users only, subject to those exclusions, neither party is liable for indirect or consequential loss, loss of profit, revenue, opportunity, goodwill or anticipated savings; our aggregate liability arising from the affected service is limited to the fees paid for that service in the 12 months before the event. Consumer liability is governed by applicable law and this business cap does not reduce mandatory consumer rights.</p></section>
    <section><h2>13. Disputes and law</h2><p>Please contact us first so we can try to resolve a concern. These Terms are governed by the law of England and Wales. Consumers may have the right to bring proceedings in the courts of the part of the UK or country where they live, and retain any non-waivable local protections. Business User disputes are subject to the exclusive jurisdiction of the courts of England and Wales unless a signed order expressly provides a lawful business-only arbitration process. No mandatory consumer arbitration is imposed by these Terms.</p></section>
    <section><h2>14. General</h2><p>Written quotes and DPAs form part of the agreement and prevail for their specific subject if inconsistent. You may not transfer the agreement without consent; we may transfer it as part of a genuine reorganisation or sale without reducing your rights. Invalid terms are severed only as necessary. Delay is not waiver. Notices may be sent to the account email; legal/privacy notices may be sent to the address below.</p></section>
    <LegalContact/>
  </LegalPage></PublicShell>;
}
