import{BadRequestException,Injectable,NotFoundException}from"@nestjs/common";import{DatabaseService}from"../database/database.service.js";
export interface CreateMeetingInput{title?:string;startsAt?:string;endsAt?:string|null;companyId?:string|null;contactId?:string|null;opportunityId?:string|null;agenda?:string|null;preparation?:string|null;notes?:string|null;outcome?:string|null;nextAction?:string|null;attendees?:unknown;}
export type UpdateMeetingInput=Partial<CreateMeetingInput>;
@Injectable()export class MeetingsService{constructor(private readonly db:DatabaseService){}async list(t:string){return this.db.tenantTransaction(t,async x=>(await x.query(
 `SELECT m."id",m."title",m."startsAt",m."endsAt",m."agenda",m."preparation",m."notes",m."outcome",m."nextAction",m."attendees",c."companyName",ct."contactName",o."opportunityName"
  FROM "Meeting" m LEFT JOIN "Company" c ON c."id"=m."companyId" LEFT JOIN "Contact" ct ON ct."id"=m."contactId" LEFT JOIN "Opportunity" o ON o."id"=m."opportunityId"
  WHERE m."tenantId"=$1::uuid ORDER BY m."startsAt" DESC LIMIT 250`,[t])).rows)}async create(t:string,b:CreateMeetingInput){if(!b.title?.trim()||!b.startsAt)throw new BadRequestException("Meeting title and start time are required.");return this.db.tenantTransaction(t,async x=>{const r=await x.query<{id:string}>(
 `INSERT INTO "Meeting" ("tenantId","companyId","contactId","opportunityId","title","startsAt","endsAt","attendees","agenda","preparation","notes","outcome","nextAction","updatedAt")
  VALUES ($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6::timestamptz,$7::timestamptz,$8::jsonb,$9,$10,$11,$12,$13,CURRENT_TIMESTAMP) RETURNING "id"`,[t,b.companyId??null,b.contactId??null,b.opportunityId??null,b.title!.trim(),b.startsAt,b.endsAt??null,b.attendees?JSON.stringify(b.attendees):null,b.agenda??null,b.preparation??null,b.notes??null,b.outcome??null,b.nextAction??null]);return{id:r.rows[0]?.id};})}async update(t:string,id:string,b:UpdateMeetingInput){return this.db.tenantTransaction(t,async x=>{const e=await x.query<{id:string}>(`SELECT "id" FROM "Meeting" WHERE "tenantId"=$1::uuid AND "id"=$2::uuid`,[t,id]);if(!e.rows[0])throw new NotFoundException("Meeting not found.");await x.query(
 `UPDATE "Meeting" SET "title"=COALESCE(NULLIF($3,''),"title"),"startsAt"=COALESCE($4::timestamptz,"startsAt"),"endsAt"=CASE WHEN $5='__unchanged__' THEN "endsAt" ELSE NULLIF($5,'')::timestamptz END,
 "agenda"=CASE WHEN $6='__unchanged__' THEN "agenda" ELSE NULLIF($6,'') END,"preparation"=CASE WHEN $7='__unchanged__' THEN "preparation" ELSE NULLIF($7,'') END,"notes"=CASE WHEN $8='__unchanged__' THEN "notes" ELSE NULLIF($8,'') END,"outcome"=CASE WHEN $9='__unchanged__' THEN "outcome" ELSE NULLIF($9,'') END,"nextAction"=CASE WHEN $10='__unchanged__' THEN "nextAction" ELSE NULLIF($10,'') END,"updatedAt"=CURRENT_TIMESTAMP WHERE "tenantId"=$1::uuid AND "id"=$2::uuid`,[t,id,b.title??"",b.startsAt??null,b.endsAt===undefined?"__unchanged__":b.endsAt??"",b.agenda===undefined?"__unchanged__":b.agenda??"",b.preparation===undefined?"__unchanged__":b.preparation??"",b.notes===undefined?"__unchanged__":b.notes??"",b.outcome===undefined?"__unchanged__":b.outcome??"",b.nextAction===undefined?"__unchanged__":b.nextAction??""]);return{updated:true};})}}
