import type { Metadata } from "next";
import Link from "next/link";
import { GRIDFLOW_LEGAL } from "@gridflow/domain";
import { LegalContact, LegalPage } from "../../../components/legal-page";
import { PublicShell } from "../../../components/public-shell";

export const metadata: Metadata = { title: "Privacy Policy | GridFlow", description: "How GridFlow collects, uses, shares and protects personal data." };

export default function PrivacyPolicyPage() {
  return <PublicShell><LegalPage eyebrow="Privacy" title="Privacy Policy" summary="How GridFlow handles account, sponsorship-workflow, public-source, integration and support data.">
    <section><h2>1. Who we are and when this policy applies</h2><p>GridFlow is operated by {GRIDFLOW_LEGAL.operatorName}. This policy applies to the GridFlow website, application, support, purchase activation and related services. Our launch scope is the United Kingdom; we do not claim universal worldwide compliance.</p><p>We are normally the <strong>controller</strong> for account, security, purchase, support, service telemetry and our own prospect data. For workspace data that a customer chooses to upload or create, we may act as a <strong>processor</strong> on that customer’s instructions. The <Link href="/legal/dpa">Data Processing Addendum</Link> covers that processor activity.</p></section>
    <section><h2>2. Data we handle</h2><ul><li><strong>Account and organisation:</strong> name, work email, password hash, role, organisation, age/authority confirmations and policy acceptance evidence.</li><li><strong>Security:</strong> session and device records, login attempts, MFA configuration, truncated device/browser information, IP address and security audit events. We do not store readable passwords, raw session tokens or raw recovery codes.</li><li><strong>Athlete and commercial workspace:</strong> profile, goals, companies, contacts, opportunities, tasks, meetings, correspondence, proposals, contracts, delivery evidence and renewal records.</li><li><strong>Public-source research:</strong> business contact details, job role, employer, public profiles, source URL, provenance, confidence and suppression/objection records.</li><li><strong>Integrations and AI:</strong> Gmail account identifiers and authorised message data; encrypted OAuth tokens; encrypted customer-provided Gemini keys; prompts, inputs, outputs, review decisions and usage/cost telemetry.</li><li><strong>Purchases and support:</strong> quote/invoice details, Wise payment reference, entitlement, activation status, receipt, support messages and privacy requests. GridFlow does not store card or bank-login credentials.</li></ul></section>
    <section><h2>3. Where data comes from</h2><p>We receive data from you, authorised organisation members, connected Gmail accounts, public company websites and professional profiles, public registers, search/research providers, AI providers, Wise payment evidence checked by an authorised administrator, and technical events produced when the service is used.</p><p>If we obtain a business contact’s personal data from a public source rather than from that person, we keep provenance and aim to provide appropriate transparency at first communication or within the period required by law. Public availability does not remove data-protection obligations.</p></section>
    <section><h2>4. Why we use data and our lawful bases</h2><div className="legal-table"><div><strong>Purpose</strong><strong>Typical basis</strong></div><div><span>Provide accounts, security, activation and purchased services</span><span>Contract; legitimate interests; legal obligation where applicable</span></div><div><span>Operate the customer’s workspace on its instructions</span><span>Customer’s documented instructions under our DPA</span></div><div><span>Research and manage relevant business sponsorship contacts</span><span>Legitimate interests, balanced against the contact’s rights</span></div><div><span>Prevent fraud, abuse, cross-tenant access and service failure</span><span>Legitimate interests; legal obligation</span></div><div><span>Support, complaints, rights and accounting records</span><span>Contract; legal obligation; legitimate interests</span></div><div><span>Optional marketing to users</span><span>Consent where required. GridFlow currently does not use pre-ticked marketing consent.</span></div></div><p>We do not use special-category data as a normal part of GridFlow. Do not upload it unless necessary, lawful and agreed with us.</p></section>
    <section><h2>5. AI, Gmail and automated assistance</h2><p>GridFlow uses AI to assist research, drafting and commercial organisation. AI output can be incomplete or wrong and remains subject to human review. The model is never the authority for access, credits, payments, sending, legal commitments or tenant boundaries.</p><p>When a user connects Gmail, GridFlow processes only the authorised data needed for the requested mailbox features. OAuth tokens are encrypted and access can be disconnected. Some Core functions use a customer-provided Gemini key, encrypted at rest; managed research can use GridFlow’s configured providers. Relevant inputs may be sent to those providers to perform the requested task. Do not place unnecessary confidential or sensitive personal data in prompts.</p></section>
    <section><h2>6. Sharing and international transfers</h2><p>We share data only with authorised organisation members, service providers needed to run GridFlow, professional advisers, authorities where legally required, or a business successor subject to appropriate safeguards. Current provider categories and purposes are listed in our <Link href="/legal/subprocessors">Subprocessor List</Link>.</p><p>Some providers may process data outside the UK. Where restricted transfers occur, we will use an available lawful safeguard such as UK adequacy regulations, the UK International Data Transfer Agreement/Addendum, or another valid mechanism, and review relevant transfer risks.</p></section>
    <section><h2>7. Retention, deletion and account closure</h2><p>We keep data only for a documented business, contractual, security or legal need. The <Link href="/legal/retention">Retention Schedule</Link> explains current periods. Account closure starts a controlled deletion workflow: active access and integrations are revoked, customer data is deleted or anonymised subject to legal holds, and limited suppression, transaction, security and acceptance evidence may be retained. Backups expire through their normal protected rotation; we do not promise instantaneous deletion from every backup copy.</p></section>
    <section><h2>8. Your choices and rights</h2><p>Depending on the law that applies, you may ask for access, correction, deletion, restriction, portability, or object to processing, and may withdraw consent without affecting earlier lawful processing. Business contacts can object to direct marketing at any time. GridFlow keeps a minimal suppression record so an opt-out is not accidentally undone.</p><p>Use the <Link href="/privacy">Privacy Centre</Link> or email {GRIDFLOW_LEGAL.supportEmail}. We may need proportionate identity verification. We will not ask for your password, MFA code, recovery code, activation token or API key.</p></section>
    <section><h2>9. Complaints</h2><p>GridFlow provides a clear electronic complaint route through the Privacy Centre. We record the complaint, acknowledge it promptly and in any event within 30 days where the UK statutory complaint duty applies, investigate it, provide updates where appropriate and respond without undue delay. You may also complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk/make-a-complaint</a>.</p></section>
    <section><h2>10. Cookies and changes</h2><p>GridFlow currently uses only strictly necessary authentication and trusted-device cookies and does not run advertising pixels or optional analytics cookies. See our <Link href="/legal/cookies">Cookie Notice</Link>. If our practices or the law change, we will update the version/date and seek renewed acceptance where a change materially affects the contract or processing.</p></section>
    <LegalContact/>
  </LegalPage></PublicShell>;
}
